### ISSUE TITLE
Nova proba para o bonus opcional 2

### ISSUE THREAD

**Issue by daavoo** [VigoTech/reto#20]
Abro Issue porque estou liándoa parda intentando facer outro pull request só con cambios no README sen joder o que xa teño aberto para a solución. xD

A cousa é que a proba recomendada no README para o bonus opcional 2 creo que non é a máis doada para evaluar a capacidade da solución.

Básicamente, ti podes crear unha solución válida que antes de probar por forza bruta todas as posibles combinacións faga un par de "checkeos" rápidos coma:
- Ver se 0 está na lista -> true
- Ver se o primeiro número da lista é > 0 -> false

Usando a segunda condición (que sería lóxico e lexítimo), a proba recomendada para o bonus 2 remata case instantáneamente e penso que pode levar confusión a hora de evaluar a capacidade do algoritmo no reto dos 300 segundos.

Propoño como proba para o bonus 2 o seguinte exemplo:

```
[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 55] - > true
```
Que non inclúe o número 0, evalúase a true, e penso que non é susceptible de resolverse con "checkeos rápidos".

Código exemplo de Python para generalo:

```python
def get_case(N):
    case = list(range(-N, 0))
    case += [abs(sum(case))]
    return case
```
E poderíase empregar incrementalmente igual que a que hai agora:

```
# get_case(11)
[-11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 66] -> true
# get_case(12)
[-12, -11, -10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 78] -> true
...
```

**Comment by antonmry** [comment]
A proba básase na boa fé, de feito, vai variar dependendo do equipo de cada un. Non é xogar o gato e o ratón ca batería de test pero vexo ben añadilo coma extra, é moi informativo.

¿Podes crear unha PR dende un branch novo? Se o ves complexo, podo intentar botarche unha man via Slack.

**Comment by daavoo** [comment]
Non se non o dicía no sentido de que alguén faga algo con mala fé. Se non que únicamente testeando co caso que hai agora no README pode levar a confusión a alguén a hora de evaluar a perfomance. 

Como exemplo pasou que :tophat:  @migonzalvar testeou empregando range(N) e entón o algoritmo remataba na primeira iteración porque el tiña como condición rápida se 0 está na lista. 

A min pasoume algo parecido co test do README porque tiña como condición rápida checkear se o primeiro número da lista é menor a 0 devolver false.

**Comment by daavoo** [comment]
Pois douche un segundo a vara por slack entón.
